---
  - hosts: all
    tasks:
      - name: backup hosts
        shell: cp /etc/hosts /etc/hosts_bak
  
      - name: sync hosts
        shell: /bin/echo {{ item }} >> /etc/hosts
        with_items:
          - 10.10.2.8 master-01
          - 10.10.2.9 master-02
          - 10.10.2.10 master-03
          - 10.10.2.11 node-01
          - 10.10.2.12 node-02
          - 10.10.2.13 node-03